apiVersion: v1
kind: Service
metadata:
  name: location-service-svc
  labels:
    run: location-service-svc
spec:
  ports:
    - port: 5002
      protocol: TCP
  selector:
    run: package-service
---
apiVersion: app/v1
kind: Deployment
metadata:
  name: location-service
spec:
  selector:
    matchLabels:
      run: location-service
  replicas: 1
  template:
    metadata:
      labels:
        run: location-service
    spec:
      containers:
      - name: package-service
        image: fipost/location-service:0.0.7.1
        ports:
        - containerPort: 5002